name: Package
on:
    push:
        branches: [ master ]
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish .aar to GitHub Packages
        run: |
         pwd
         ls
         echo "lsed"
         mvn deploy:deploy-file -Dfile=iden3mobile.aar -Durl=https://maven.pkg.github.com/arnaubennassar/gh-actions-playground -DrepositoryId=github -DrepositoryName="GitHub Pages" -Dfiles=iden3mobile-sources.jar -Dtypes=jar -Dclassifiers=sources,tests -DgroupId=com.arnaubennassar.test -DartifactId=testi3 -Dversion=1 -Dpackaging=aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
