name: Package
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    # - name: run tests
    #   uses: reactivecircus/android-emulator-runner@v2
      env:
        github: ${{secrets.GH_AUTH}}
        infura: ${{secrets.INFURA_TOKEN}}
      run: cd android && echo $github > iden3coreapi/github.properties && echo $infura > iden3coreapi/infura.properties && cat iden3coreapi/infura.properties
      # with:
      #   api-level: 29
      #   script: cd android && echo $github > iden3coreapi/github.properties && echo $infura > iden3coreapi/infura.properties && cat iden3coreapi/infura.properties
