name: Package
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: inject-secrets
      id: inject-secrets
      run: echo "${{secrets.GH_AUTH}}" > android/iden3coreapi/github.properties && echo '${{secrets.INFURA_TOKEN}}' > android/iden3coreapi/infura.properties

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: adb logcat GoLog:D fullFlow:D \*:S -v long > android/logcat.log & cd android && ./gradlew iden3coreapi:connectedAndroidTest ; if [ $? -eq 0 ]; then success=0; else success=1; fi pkill adb && cat logcat.log && rm logcat.log ; if [ $success -eq 1 ]; then executionFailed; fi
