name: Package
on:
    push:
        branches: [ master ]

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish .aar to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        mkdir -p /tmp/builds
        cp /root/actions-playground/iden3mobile.aar /tmp/builds
        cp /root/actions-playground/pom.xml /tmp/builds
        cd /tmp/builds
        mvn deploy
        
        