name: Package
on:
    push:
        branches: [ master ]
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Last Version
        id: last_version
        run: |
          echo ::set-output name=version::$(git tag --list 'v*' | sort --version-sort | tail -n 1 | cut -c2-)
      - name: Bump Version
        id: bump_version
        uses: ed255/increment-semantic-version@master
        with:
          current-version: ${{ steps.last_version.outputs.version }}
          version-fragment: beta

      - name: Next Version
        id: next_version
        run: |
          echo ::set-output name=version::v${{ steps.bump_version.outputs.next-version }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish .aar to GitHub Packages
        run: |
         mvn deploy:deploy-file -Dfile=iden3mobile.aar -Durl=https://maven.pkg.github.com/arnaubennassar/gh-actions-playground -DrepositoryId=github -DrepositoryName="GitHub Pages" -Dfiles=iden3mobile-sources.jar -Dtypes=jar -Dclassifiers=sources -DgroupId=com.arnaubennassar.test -DartifactId=testi3 -Dversion="${{ steps.next_version.outputs.version }}" -Dpackaging=aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
