name: Package
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: inject-secrets
      id: inject-secrets
      run: echo "${{secrets.GH_AUTH}}" > android/iden3coreapi/github.properties && echo '${{secrets.INFURA_TOKEN}}' > android/iden3coreapi/infura.properties


    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: |
          echo "===== 1st STEP" && adb logcat GoLog:D fullFlow:D \*:S -v long > android/logcat.log &
          echo "===== 2nd STEP" && cd android && ./gradlew iden3coreapi:connectedAndroidTest
          echo "===== 3rd STEP" && pwd && pkill adb && cat logcat.log && rm logcat.log
