name: Package
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: inject-secrets
      id: inject-secrets
      env:
        github: ${{secrets.GH_AUTH}}
        infura: ${{secrets.INFURA_TOKEN}}
      run: echo "${{secrets.GH_AUTH}}" && echo $github > android/iden3coreapi/github.properties && echo $infura > android/iden3coreapi/infura.properties


    # - name: run tests
    #   uses: reactivecircus/android-emulator-runner@v2
    #   with:
    #     api-level: 29
    #     script: cat android/iden3coreapi/github.properties && cd android && ./gradlew iden3coreapi:connectedAndroidTest
